module.exports = {
    SECRET_FOR_TOKEN: 'SECRET_FOR_TOKEN',
    ACCESSTOKEN_EXPIRE: '20m',
};
module.exports.activityTypes = {
    CREATE_CARD: 'CREATE_CARD',
    DELETE_CARD: 'DELETE_CARD',
    CREATE_LIST: 'CREATE_LIST',
    DELETE_LIST: 'DELETE_LIST',
    RENAME_LIST: 'RENAME_LIST',
    REPLACE_CARD: 'REPLACE_CARD',
    ADD_COMMENT: 'ADD_COMMENT',
};
